version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - unconvert

  settings:
    misspell:
      locale: US

run:
  timeout: 5m
